version: '3.8'
services:

  volume-init:
    image: busybox
    command: sh -c "mkdir -p /var/lib/postgresql/data && chmod -R 777 /var/lib/postgresql/data"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432  # make sure you don't have another container running on 5432
    environment:
      - POSTGRES_DB=myDB
      - POSTGRES_USER=tushar
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tushar"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - volume-init
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  app:
    image: tusharna/cicd:latest
    build: .
    restart: always
    ports:
      - 3006:3006
    depends_on:
      - db
    env_file:
      - .env      

  