name: Docker Image CI

on:
  push:
    branches: [ "cicd" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_USERNAME/cicd:$(date +%s)
        
      - name: Push the Docker image
        run: docker push $DOCKER_USERNAME/cicd:$(date +%s)

