name: Docker Image CI

on:
  push:
    branches: [ "cicd" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker image using Docker Compose
        run: docker compose build

      - name: Tag the app image
        run: docker tag nepelkrecs-app ${{ secrets.DOCKER_USERNAME }}/cicd:latest

      - name: Push the Docker image
        run: docker push $DOCKER_USERNAME/cicd:latest

  cd:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull tusharna/cicd:latest

      - name: Delete old Docker image
        run: sudo docker rm -f cicd

      - name: Run Docker Container
        run: sudo docker run -d --name cicd -p 3006:3006 tusharna/cicd

